# Generated by Django 3.2.25 on 2025-11-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=21)),
                ('company', models.CharField(max_length=21)),
                ('des', models.CharField(max_length=12)),
                ('location', models.CharField(max_length=21)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
