# Generated by Django 3.2.25 on 2025-11-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=21)),
                ('sec', models.CharField(max_length=12)),
                ('J_date', models.DateField()),
                ('gender', models.CharField(max_length=12)),
            ],
        ),
    ]
