# Generated by Django 3.2.25 on 2025-11-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=12)),
                ('company', models.CharField(max_length=12)),
                ('designation', models.CharField(max_length=12)),
                ('J_date', models.DateField()),
            ],
        ),
    ]
